### ISSUE TITLE
Output while exiting legion

### ISSUE THREAD

**Issue by pdelteil** [carlospolop/legion#1]
Hey there,

This is a very good tool. I'm having a strange behavior, after the scan on a host finishes and I quit legion some output (from the scans) appears:

![Screenshot from 2019-09-17 12-38-33](https://user-images.githubusercontent.com/20244863/65057752-788f2d80-d949-11e9-8ad8-07295ac0aa71.png)

**Comment by Davincible** [comment]
The tool didn't finish yet, the `http_dirhunt_80` was probably still running, and that is the output you are seeing. You can check which commands are still running by typing `procs` in the interactive legion console

**Comment by carlospolop** [comment]
Hey guys,
I'm sorry for the waiting, somehow I wasn't watching my own project and I didn't received any notification about any issue.
Anyway, this bug should have been fixed some months ago.
Could you confirm that?
