### ISSUE TITLE
How can I run legion using the command line?

### ISSUE THREAD

**Issue by pdelteil** [carlospolop/legion#2]
Hello there,

I've been trying to run legion without getting into the console. 

So far, I managed to set the host but not able to run it, I don't know if it's possible. 

My attempt:

`legion  --host host.domain -i 2 -r startGeneral
`

That's my idea of how to run it, but it doesn't work. I also tried:

`legion  --host host.domain -i 2 -r  
`

Gives me the error 
TypeError: main_run() missing 1 required positional argument: 'exec'

**Comment by Davincible** [comment]
You could take a look at the legion.py to see how it works, but your last command should work, however, there is a small bug. If you append an empty string `""` argument to line 73, it will work.

What line 73 then will look like:
```password, ipv6, domain, interactive, verbose, False, [], "")```

**Comment by carlospolop** [comment]
Hey guys,
As I've already told you, I'm sorry for the waiting, somehow I wasn't watching my own project and I didn't received any notification about any issue.
Anyway, thanks for the issue @pdelteil and thank you very much @Davincible or the workaround.
I have updated legion to support the param `--execonly` and this bug should be fixed now.
Please, if you could confirm so.
