### ISSUE TITLE
Create Dockerfile for legion

### ISSUE THREAD

**Issue by alegrey91** [carlospolop/legion#5]
I think could be really comfortable create a `Dockerfile` for **legion** to have a ready-to-run container out of the box.
If you want, I can take care of it.

**Comment by carlospolop** [comment]
Hey @alegrey91,

That would be awesome.
It will be perfect if could create a working Docker file and make a pull request.
Thanks man.

**Comment by alegrey91** [comment]
Perfect, @carlospolop.
I'll send you a pull request when Dockerfile will be ready.

**Comment by alegrey91** [comment]
@carlospolop the `Dockerfile` draft is ready, but I think the `install.sh` have to be enhanced.
A lot of utility that `legion` is using are not present into the installation script, and manage them from the `Dockerfile` could be really tricky. I think, a good idea could be to separate legion utilities installation (metasploit, smbclient, etc..) into `install.sh` and  system dependencies (git, python3, etc..) into `Dockerfile`.
If you can enhance `install.sh`, I can focus on Dockerfile implementation.

**Comment by carlospolop** [comment]
Hmmm, I don't think that it's a good idea to automate the installation of metasploit inside a script.
Why don't you use a metasploit docker image, or even a kali docker image as base image and on top of that you run the `install.sh` script file. Probably those images comes with most of the system dependencies already installed.

**Comment by alegrey91** [comment]
Yes, nice idea. I'll try this asap.

**Comment by carlospolop** [comment]
Thanks man, that worked perfectly.
I just have made small changes in the Readme, I hope you don't mind.

**Comment by alegrey91** [comment]
Of course, no 😎
