### ISSUE TITLE
nikto and other tools are missing from Docker build

### ISSUE THREAD

**Issue by mavensecurity** [carlospolop/legion#7]
Using the Dockerfile results in a container that is missing:
* nitko
* cmsmap
* wafw00f
* whatweb

Example:
```
# cat https_cmsmap_443.err
/bin/sh: 1: cmsmap: not found
```

It also seems like a wordlist is missing:
```
# cat http_medium_dirsearch_80.out
The wordlist file does not exist
```

**Comment by carlospolop** [comment]
Hey @alegrey91 
Could you take a look to this?

**Comment by alegrey91** [comment]
Of course @carlospolop. I'll fix this asap 👍

**Comment by alegrey91** [comment]
Hi @carlospolop, I found a little issue due to utilization of some wordlists.
The wordlist `/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt` (line 44 of http_warrior.py file) needs the pkg `dirbuster` to be downloaded.
Download `dirbuster` only to use its wordlist seems to be useless.
What do you think about?

**Comment by carlospolop** [comment]
Hi @alegrey91,

Maybe we could upload that list to this github and download it dynamically from here with a wget. Anyway, in your pull request you installed dirb right? that's also okey.
Was this issue completely fixed with your pull request?

**Comment by alegrey91** [comment]
Yes @carlospolop, I installed `dirb` to download the relative worldlists used from legion.
We can think to some kind of future enhancement to provide the right wordlists without install their tools. For example we could use other (not too different from originals) wordlists taken from `SecLists`, or as you suggested push these wordlists inside `legion` repo directly.

**Comment by mavensecurity** [comment]
Maybe just add `dirb` to the list of tools used by `legion`, unless there is already a better option included.

**Comment by carlospolop** [comment]
I have added `dirb` to legion default installation also.
Thank you @mavensecurity for noticing the bug and thank you very much @alegrey91 for fixing it.
